// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidClassGeneratorPackageString = "0f3849a4-4e3f-427b-8691-00f61a4a73b3";
        public static Guid guidClassGeneratorPackage = new Guid(guidClassGeneratorPackageString);

        public const string guidClassGeneratorPackageCmdSetString = "e7f13fbc-5d0b-4152-90f2-c4b654e8cf09";
        public static Guid guidClassGeneratorPackageCmdSet = new Guid(guidClassGeneratorPackageCmdSetString);

        public const string guidImagesString = "1cb36c58-2f91-4318-8362-24ea0d606836";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GenerateId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}